export type PaymentReceiptData = {
  id?: number | string;
  student_name?: string;
  student_id?: string;
  email?: string;
  program_name?: string;
  package_name?: string;
  amount?: number | string;
  method?: string;
  payment_method?: string;
  status?: string;
  created_at?: string;
  payment_date?: string;
  provider_transaction_id?: string;
  transaction_id?: string;
  payer_phone?: string;
  currency?: string;
};

function formatMoney(amount?: number | string) {
  return `$${Number(amount || 0).toFixed(2)}`;
}

function formatDate(value?: string) {
  if (!value) return "N/A";
  return new Date(value).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatMethod(row: PaymentReceiptData) {
  const method = (row.payment_method || row.method || "N/A").toUpperCase();
  if (method.includes("WAAFI")) return "WAAFI";
  if (method === "EVC") return "EVC";
  if (method === "BANK") return "BANK";
  return method;
}

export function buildPaymentReceiptHtml(row: PaymentReceiptData) {
  const txId = row.transaction_id || row.provider_transaction_id || `PAY-${row.id || "N/A"}`;
  const title = row.package_name || row.program_name || "BEA Payment";

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>BEA Payment Receipt - ${txId}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111; margin: 0; padding: 32px; }
    .wrap { max-width: 720px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 12px; overflow: hidden; }
    .head { background: #010080; color: #fff; padding: 24px 28px; }
    .head h1 { margin: 0 0 6px; font-size: 22px; }
    .head p { margin: 0; opacity: 0.9; font-size: 13px; }
    .body { padding: 28px; }
    .amount { font-size: 34px; font-weight: 800; color: #010080; margin: 0 0 8px; }
    .status { display: inline-block; padding: 4px 10px; border-radius: 999px; font-size: 11px; font-weight: 700; text-transform: uppercase; background: #dcfce7; color: #166534; }
    table { width: 100%; border-collapse: collapse; margin-top: 24px; }
    td { padding: 10px 0; border-bottom: 1px solid #f1f5f9; font-size: 14px; vertical-align: top; }
    td.label { width: 38%; color: #64748b; font-weight: 600; }
    .foot { padding: 18px 28px 24px; font-size: 11px; color: #64748b; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <div class="wrap">
    <div class="head">
      <h1>BEA — The Blueprint English Academy</h1>
      <p>Official Payment Receipt</p>
    </div>
    <div class="body">
      <p class="amount">${formatMoney(row.amount)}</p>
      <span class="status">${(row.status || "paid").toString()}</span>
      <table>
        <tr><td class="label">Receipt #</td><td>${txId}</td></tr>
        <tr><td class="label">Student</td><td>${row.student_name || "N/A"}${row.student_id ? ` (${row.student_id})` : ""}</td></tr>
        ${row.email ? `<tr><td class="label">Email</td><td>${row.email}</td></tr>` : ""}
        <tr><td class="label">Description</td><td>${title}</td></tr>
        <tr><td class="label">Payment Method</td><td>${formatMethod(row)}</td></tr>
        ${row.payer_phone ? `<tr><td class="label">Payer Phone</td><td>${row.payer_phone}</td></tr>` : ""}
        <tr><td class="label">Date</td><td>${formatDate(row.payment_date || row.created_at)}</td></tr>
      </table>
    </div>
    <div class="foot">
      This receipt was generated by BEA E-Learning. Keep it for your records.
    </div>
  </div>
  <script>window.onload = function(){ window.print(); };</script>
</body>
</html>`;
}

export function downloadPaymentReceipt(row: PaymentReceiptData) {
  const html = buildPaymentReceiptHtml(row);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const txId = row.transaction_id || row.provider_transaction_id || row.id || "receipt";
  const link = document.createElement("a");
  link.href = url;
  link.download = `BEA-Receipt-${txId}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function printPaymentReceipt(row: PaymentReceiptData) {
  const html = buildPaymentReceiptHtml(row);
  const win = window.open("", "_blank", "noopener,noreferrer,width=900,height=700");
  if (!win) {
    downloadPaymentReceipt(row);
    return;
  }
  win.document.write(html);
  win.document.close();
}
